import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Home from "../components/home/Home";

export default function Homepage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css?family=Lato"
          rel="stylesheet"
        />
        <script
          src="https://kit.fontawesome.com/c8e4d183c2.js"
          crossOrigin="anonymous"
        ></script>

        <link
          rel="stylesheet"
          href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css"
        ></link>
      </Head>

      <main>
        <Home />
      </main>
    </div>
  );
}
