import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { wrapper } from "../redux/store";
import { LoadUser } from "../redux/actions/userActions";
import { Cookie } from "next-cookie";
import Home from "../components/home/Home";

export default function Homepage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css?family=Lato"
          rel="stylesheet"
        />
        <script
          src="https://kit.fontawesome.com/c8e4d183c2.js"
          crossOrigin="anonymous"
        ></script>

        <link
          rel="stylesheet"
          href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css"
        ></link>
      </Head>

      <main>
        <Home />
      </main>
    </div>
  );
}

//use this serverside method when u are  bothered abt server side rednering of ur data through redux store.
// we want to load user details want de land on home page
export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async ({ req }) => {
      const cookies = Cookie.fromApiRoute(req);

      const token = cookies.get("token");
      // const sess = await getSession({ req });

      // console.log(token);

      if (token) {
        await store.dispatch(LoadUser(req, token));
        console.log("Theres token");
      }
    }
);
