export const NEW_SHIPMENT_REQUEST = "NEW_SHIPMENT_REQUEST";
export const NEW_SHIPMENT_SUCCESS = "NEW_SHIPMENT_SUCCESS";
export const NEW_SHIPMENT_FAIL = "NEW_SHIPMENT_FAIL";
export const NEW_SHIPMENT_RESET = "NEW_SHIPMENT_RESET";

export const MY_SHIPMENTS_REQUEST = "MY_SHIPMENTS_REQUEST";
export const MY_SHIPMENTS_SUCCESS = "MY_SHIPMENTS_SUCCESS";
export const MY_SHIPMENTS_FAIL = "MY_SHIPMENTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
